_commit: 9c2eb86
_src_path: gh:monarch-initiative/cookiecutter-monarch-ingest
copyright_year: '2026'
email: info@monarchinitiative.org
full_name: Monarch Initiative
github_handle: monarch-initiative
github_org: monarch-initiative
license: BSD-3-Clause
project_description: HGNC human gene ingest
project_name: hgnc-ingest
project_slug: hgnc_ingest
